import type { Metadata } from "next";
import StoreProvider from "@/store/provider";
import GraphQLProvider from "@/providers/graphqlProvider";
import DefaultLayout from "@/components/_shared/Layout/RootLayout";
import "./globals.css";

export const metadata: Metadata = {
  title: "DevCollab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body>
      <GraphQLProvider>
        <StoreProvider>
          <DefaultLayout>
            {children}
          </DefaultLayout>
          </StoreProvider>
      </GraphQLProvider>
      </body>
    </html>
  );
}
