import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DevCollab",
  description: "Generated by create next app",
  keywords: "lập trình, code cùng nhau, realtime coding, Monaco Editor",
  openGraph: {
    title: "Code Together",
    description: "Chia sẻ, viết code cùng nhau với Monaco Editor trong thời gian thực.",
    url: "https://yourwebsite.com",
    siteName: "Code Together",
    images: [
      {
        url: "https://yourwebsite.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Code Together - Cộng tác lập trình",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Code Together",
    description: "Chia sẻ, viết code cùng nhau với Monaco Editor trong thời gian thực.",
    images: ["https://yourwebsite.com/og-image.jpg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body>
       {children}
      </body>
    </html>
  );
}
