name: DEVCOLLAB-FE

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install dependencies
        run:  yarn install

      - name: Run Test
        run: yarn test

      - name: Build App
        run: yarn build